name: simple

services:
  app:
    build: ./app
    ports:
      - "5050:3000"
    volumes:
      - vol-simple:/app/public/images/
    networks:
      - jenkins-net

  sonarqube:
    image: sonarqube:9.9.1-community
    container_name: simple-sonarqube
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    deploy:
      resources:
        limits:
          memory: 2g
    networks:
      - jenkins-net

  db:
    image: postgres:15
    container_name: simple-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - jenkins-net

  jenkins:
    build: ./jenkins
    container_name: simple-jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Jenkinsfile:/var/jenkins_home/Jenkinsfile:ro
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped
    networks:
      - jenkins-net

  dind:
    image: docker:24-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    ports:
      - "2375:2375"
    volumes:
      - dind_data:/var/lib/docker
    networks:
      - jenkins-net

  agent:
    build: ./jenkins-agent
    container_name: simple-agent
    depends_on:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://dind:2375
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=devops1-agent
      - JENKINS_SECRET=572933c875c0d93f3edcac102f3d2e31c1bead3106d17cc49bb3b42ef0c94229
    networks:
      - jenkins-net
    restart: unless-stopped

volumes:
  vol-simple:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres_data:
  jenkins_home:
  dind_data:

networks:
  jenkins-net:
    driver: bridge
